#!/bin/bash
#+#aur-helperfunction
#+
#+   Provides bash functions which help managing a local repo of AUR packages
#+ 
#+#Provided Functions

aur-get () {
	#+ downloads sources for package from AUR
	if [[ -z "$1" ]] || ! [[ "$1" =~ ^[[:alpha:][:digit:]-]*$ ]]; then return 1; fi

	echo 'getting package '$1' from AUR'
	pushd "$SRCDIR" || return 1

	if [[ -d "$PKGBUILDIR/prev" ]]; then
		local PREV="$PKGBUILDIR/prev/$1"
		[[ -d "$PKGBUILDIR/$1" ]] && { rm -rf "$PREV"; mv "$PKGBUILDIR/$1" "$PREV"; }
		[[ -e "$1.tar.gz" ]] && { rm -f "$PREV.tar.gz"; mv "$1.tar.gz" "$PREV.tar.gz"; }
	else
		rm rf "$PKGBUILDIR/$1"
		rm -f "$1.tar.gz"
	fi

	if wget "https://aur.archlinux.org/packages/${1:0:2}/$1/$1.tar.gz"; then
		tar -xf "$SRCDIR/$1.tar.gz" -C "$PKGBUILDIR" &&\
		cd "$PKGBUILDIR/$1" && {
			local COLN="\033[0m" COLE="\033[1;39m"
			if [[ -d "$PREV" ]]; then
				echo -e "${COLE}diff from old version:${COLN}"
				diff -r "$PREV" .
				echo -e "${COLE}end diff${COLN}"
			else
				echo -e "${COLE}files in current directory${COLN}"
				ls
				echo -e "${COLE}PKGBUILD:${COLN}"
				cat PKGBUILD
				echo -e "${COLE}end PKGBUILD${COLN}"
			fi
			true
		}
	else
		false
	fi

	if (($?!=0)); then
		echo "error $1" >&2
		pushd
		false
	fi
}

aur-local-packages () {
	#+ prints list of installed packages from local repo
	#+ `-a` print all packages, including those in repo but not installed
	#+ `-e` exclude packages from EXCLUDE variable

	local pacout=$( LANG=C pacman -Sl "$REPONAME" )
	local optallpkg="" optexclude=""
	while (($#>0)); do
		case "$1" in
			"-a" ) optallpkg=yes;;
		  	"-e" ) optexclude=yes;;
		esac
		shift
	done

	if [[ "$optexclude" ]] && [[ "$EXCLUDE" ]]; then
		if [[ -e "$EXCLUDE" ]] && [[ "${EXCLUDE:0:1}" == "/" ]] ; then
			pacout=$( grep -v -F -f "$EXCLUDE" <<<"$pacout" )
		else
			local excludes=$( sed -e 's/,/\n/g' <<<"$EXCLUDE" )
			pacout=$( grep -v -F -e "$excludes" <<<"$pacout" )	
		fi
	fi
	if [[ "$optallpkg" ]]; then
		awk -F " " '{ print $2,$3;}' <<<"$pacout"
	else
		awk -F " " '/installed/ { print $2,$3;}' <<<"$pacout"
	fi
}

aur-search () {
	#+ searches packages matching string on AUR

	local json="$( wget "https://aur.archlinux.org/rpc.php?type=search&arg=$1" -o /dev/null -O - )"

	if [[ ! "$json" ]] || grep -q error <( jshon <<<"$json" -e type ); then
		echo "Failed to search $1"
		return 1
	fi
	local resultsn=$( jshon <<<"$json" -e results -l )
	echo "${resultsn-No} matching packages in AUR"
	if [[ ! "$resultsn" ]] || [[ "$resultsn" == 0 ]]; then return 1; fi

	exec 3< <( jshon <<<"$json" -e results -a -e Name -u )
	exec 4< <( jshon <<<"$json" -e results -a -e Description -u )
	exec 5< <( jshon <<<"$json" -e results -a -e Version -u )
	local name description version
	while read name <&3 && read description <&4 && read version <&5; do
		echo -e "$name $version\n    $description"
	done
	exec 3<&- 4<&- 5<&-
}

aur-info () {
	#+ gets package info from AUR
	#+ aur-info [-a] package1 [package2 [...]]
	#+ `-a` fills version array (if run as standalone, declare it with "local -A aurversion aurmaint" beforehand)

	if [[ "$1" == "-a" ]]; then
		shift
		local getver=yes
	fi

	local args=""
	local pkg
	for pkg in "$@"; do
		args+='&arg[]='"$pkg"
	done
	local json="$( wget "https://aur.archlinux.org/rpc.php?type=multiinfo${args}" -o /dev/null -O - )"

	if [[ ! "$json" ]] || grep -q error <( jshon <<<"$json" -e type ); then
		echo "Failed to get any AUR info"
		return 1
	fi
	if [[ "$( jshon <<<"$json" -e results -l )" == 0 ]]; then
		echo "0 matching packages in AUR"
		return 1
	fi

	if [[ ! "$getver" ]]; then
		jshon <<<"$json" -e results
	else
		exec 3< <( jshon <<<"$json" -e results -a -e Name -u )
		exec 4< <( jshon <<<"$json" -e results -a -e Version -u )
		exec 5< <( jshon <<<"$json" -e results -a -e Maintainer )

		while read name <&3 && read version <&4 && read maint <&5; do
			aurversion["$name"]="$version"
			aurmaint["$name"]="$maint"
		done
		exec 3<&- 4<&- 5<&-
	fi
}

aur-check () {
	#+ checks for updates on AUR
	#+ `-a` to check every package in repo (including not installed)
	#+ `-v` verbose output: prints also packages already up to date
	#+ if packagenames are provided after options, check those in spite of local repo

	local allpkg="" showall=""
	while [[ "${1:0:1}" == "-" ]]; do
		case "$1" in
			"-v" ) showall=yes;;
			"-a" ) allpkg="-a";;
			* ) break;;
		esac
		shift
	done

	local listupdated=() listtoupdate=() listnotfound=() listnotmaintained=()
	local dropped=""
	
	dropped=$( pacman -Qqm )

	local packagestocheck
	if (($#==0)); then
		packagestockeck=$( aur-local-packages -e "$allpkg" )
	else
		packagestockeck=$( pacman -Q "$@" 2>/dev/null )
	fi
	if [[ -z "$packagestockeck" ]]; then
		echo "No package to check" >&2
		return 1
	fi

	local -A localversion=() 
	local -a packages=()
	local package version
	while read package version; do
		packages+=("$package")
		localversion["$package"]="$version"
	done <<<"$packagestockeck"
	
	local -A aurversion=()
	local -A aurmaint=()
	aur-info -a "${packages[@]}"
	(($?==1)) && return 1

	local aur loc
	for package in "${packages[@]}"; do
		loc="${localversion["$package"]}"
		aur="${aurversion["$package"]}"
		if [[ "$aur" ]]; then
			r=$( vercmp "$loc" "$aur" )
			if ((r==0)); then
				listupdated+=("$package")
			elif ((r>0)); then
				listupdated+=("$package ($loc > $aur)")
			else
				listtoupdate+=("$package ($loc < $aur)")
			fi
			if [[ "${aurmaint["$package"]}" == null ]]; then
				listnotmaintained+=("$package" )
			fi
		else
			listnotfound+=("$package")
		fi
	done
	
	local return=1
	local OLDIFS="$IFS"
		IFS=$'\n'
		local COLG="\033[1;32m" COLR="\033[1;31m" COLN="\033[0m" COLE="\033[1;39m"
		[[ "$showall" ]] && ((${#listupdated[@]}>0)) &&\
			echo -e "${COLG}Updated${COLN}\n${listupdated[*]}${COLN}"
		((${#listnotmaintained[@]}>0)) &&\
			echo -e "${COLR}Unmaintained${COLN}\n${listnotmaintained[*]}${COLN}" && return=0
		((${#dropped}>0)) &&\
			echo -e "${COLR}Dropped from repos${COLN}\n${dropped}${COLN}" && return=0
		((${#listnotfound[@]}>0)) &&\
			echo -e "${COLR}Not found in AUR${COLN}\n${listnotfound[*]}${COLN}" && return=0
		((${#listtoupdate[@]}>0)) &&\
			echo -e "${COLR}To update${COLE}\n${listtoupdate[*]}${COLN}" ||\
			echo -e "${COLG}None to update${COLN}"
	IFS="$OLDIFS"
	(($return&${#listtoupdate[@]}==0))
}

aur-sobump () {
	#+ checks if any local package has binaries depending from given libraries
	#+ `-p` to check all libraries in given packages
	#+ ex: aur-sobump libz.so
	#+ ex: aur-sobump -p zlib
	local pkg i provided linked linkedraw found LINKER
	local -a packages=()

	if [[ "$1" == "-p" ]]; then
		shift
		if (($#>0)); then
			provided=$( pacman -Qql "$@" | while read i; do basename "$i"; done )
		fi
	else
		provided=( "$@" )
	fi
	if ((${#provided}==0)); then
		echo "input error" >&2 
		return 1
	fi
	
	while read pkg; do
		packages+=( "$pkg" )
	done < <( aur-local-packages | cut -f 1 -d " " )

	for pkg in "${packages[@]}"; do
		needed=$(
			for i in $( pacman -Qql $pkg ); do
				for LINKER in /lib/ld-linux-x86-64.so.2 /lib/ld-linux.so.2; do
					if $LINKER --verify "$i" >/dev/null ; then
						LANG=C readelf -d "$i" | sed -n -e 's/.*NEEDED.*\[\(.*\)\]$/\1/p'
					fi
				done
			done
		)

		found=$( comm -12 <( sort -u <<<"$needed" ) <( sort -u <<<"$provided" ) )
		if ((${#found}>0)); then
			echo -e "$pkg depends on:\n$found\n"
		fi
	done
}

aur-depcheck () {
	#+ checks for missing dynamic libraries

	local pkg i missing outraw outpac LINKER
	local -a packages
	if (($#>0)); then
		packages=("$@")
	else
		packages=( $( aur-local-packages | cut -f 1 -d " " ) )
	fi

	for pkg in "${packages[@]}"; do
		for i in $( pacman -Qql $pkg ); do
			for LINKER in /lib/ld-linux-x86-64.so.2 /lib/ld-linux.so.2; do
				if $LINKER --verify "$i" >/dev/null ; then	
					missing=$( $LINKER --list "$i" 2>&1 | grep "error while loading shared libraries" | cut -f 1,3 -d ':')
					if (( ${#missing} != 0 )); then
						outraw+="$missing"$'\n'
						outpac+=" $pkg"$'\n'
					fi
				fi
			done
		done
	done

	if ((${#outraw}>0)); then
		echo 'Missing libraries'
		cut -f 2 -d ':' <<<"$outraw" | sort -u | grep -v "^$"
		echo
		echo 'Possible Rebuilds'
		sort -u <<<"$outpac" | grep -v "^$"
	else
		echo "No missing libraries"
	fi

}

repo-upd () {
	#+ updates local repo adding most recently built packages
	repo-add $(find "$REPODIR" -mtime -1 -type f -iname '*.tar.xz' )
}

repo-add () {
	#+ repo-add package.tar.xz
	#+ adds package to local repo
	command repo-add "$REPODB" "$@"
}

repo-remove () {
	#+ repo-remove package
	#+ removes package from local repo
	command repo-remove "$REPODB" "$@"
}

makepkg () {
	#+ wraps makepkg copying most recently built package to local repo

	export PKGDEST="${REPODIR}"
	if command makepkg "$@"; then
		if [[ "$REPOADDALL" ]]; then 
			repo-add *.tar.xz
		else
			files=(*.tar.xz)
			file=$( ( IFS=$'\n'; sort -V <<<"${files[*]}"; ) | tail -n 1 )
			[[ -e "$file" ]] && repo-add "$file"
		fi
	fi
}

CONFIGFILE="${XDG_CONFIG_HOME:-$HOME/.config}/aur-helperfunctions.conf"

if [[ -f "$CONFIGFILE" ]]; then
	. "$CONFIGFILE"
else
	if ! [[ "$REPONAME" ]]; then
		echo "please configure $CONFIGFILE and resource before doing anything" >&2
		echo "see /etc/aur-helperfunctions.conf for example configuration" >&2
		false
	fi
fi

: ${REPONAME:=aur}
: ${REPODIR:=$HOME/aur/repo}
: ${REPODB:=$REPODIR/${REPONAME}.db.tar.gz}
: ${SRCDIR:=$HOME/aur/src}
: ${PKGBUILDIR:=$HOME/aur/src}
: ${EXCLUDE:=$HOME/aur/exclude}

for dir in "${SRCDIR}" "${REPODIR}" "${PKGBUILDIR}"; do
	if [[ ! -d "$dir" ]]; then
		echo "missing directory: $dir" >&2
		echo "fix before doing anything" >&2
	fi
done

if ! type jshon >/dev/null 2>&1; then
	echo "jshon is required for aur-{check,search,info}: install it before running them" >&2
fi

if ! grep -q "[$REPONAME]" /etc/pacman.conf; then
	# tells how to add local repo to /etc/pacman.conf
	cat >&2 <<-END
		# repo $REPONAME not configured in pacman.conf 
		# paste and run this from a root shell, or add to pacman.conf the lines between EOFs
		cat >> /etc/pacman.conf <<EOF

		[$REPONAME]
		SigLevel = Optional TrustAll
		Server = file://$REPODIR
		EOF
	END
fi
